# Generated by Django 2.2 on 2022-12-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hd_laodong',
            name='Hieuluc',
            field=models.BooleanField(default=True),
        ),
    ]
