# Generated by Django 2.2 on 2023-02-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0005_auto_20221230_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hd_laodong',
            name='Bac',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Bo_nhiem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Dieudong',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Hieuluc',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Ho_ten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien'),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Ht_traluong',
            field=models.CharField(blank=True, choices=[('Khoán', 'Khoán'), ('Thời gian', 'Thời gian'), ('Sản phẩm', 'Sản phẩm')], default='Khoán', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Loai_hd_coth',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Loai_hd_kth',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Loai_hd_thu_viec',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Ly_do',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Nang_luong',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='Ngay_nangluong_sau',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hd_laodong',
            name='bangluong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luong.bangluong'),
        ),
    ]
