# Generated by Django 2.2 on 2023-02-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_nhan_vien_da_nghiviec'),
        ('luong', '0006_auto_20230201_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='hd_laodong_thu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('So_hopdong', models.CharField(max_length=20, null=True)),
                ('Ho_ten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien')),
            ],
        ),
    ]
