# Generated by Django 2.2 on 2023-02-01 02:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0007_hd_laodong_thu'),
    ]

    operations = [
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Bac',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Bo_nhiem',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Den_ngay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Dieudong',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Heso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Hieuluc',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Hoten_nhanvien',
            field=models.CharField(blank=True, default='Họ tên', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Ht_traluong',
            field=models.CharField(blank=True, choices=[('Khoán', 'Khoán'), ('Thời gian', 'Thời gian'), ('Sản phẩm', 'Sản phẩm')], default='Khoán', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Loai_hd',
            field=models.CharField(choices=[('Có thời hạn', 'Có thời hạn'), ('Không thời hạn', 'Không thời hạn'), ('Thử việc', 'Thử việc')], default='Không thời hạn', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Loai_hd_coth',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Loai_hd_kth',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Loai_hd_thu_viec',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Ly_do',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Muc_luong',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Nang_luong',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Ngay_nangluong_sau',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Thu_nhap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='Tu_ngay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='bangluong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luong.bangluong'),
        ),
        migrations.AddField(
            model_name='hd_laodong_thu',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 1, 2, 15, 0, 527740, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
