# Generated by Django 2.2 on 2023-03-12 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0009_bangluong_chinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangluong_chinh',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bangluong_chinh',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 12, 9, 15, 58, 962267, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
