# Generated by Django 2.2 on 2023-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0010_auto_20230312_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangluong_chinh',
            name='Luong_bac_1',
            field=models.IntegerField(null=True),
        ),
    ]
