# Generated by Django 2.2 on 2023-03-15 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0018_auto_20230314_2214'),
        ('enroll', '0003_nhan_vien_da_nghiviec'),
        ('luong', '0012_bangluong_bhxh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phuongan_luong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Luong_BHXH_cu', models.IntegerField(null=True)),
                ('Luong_cu', models.IntegerField(null=True)),
                ('Bac_1', models.IntegerField(null=True)),
                ('Bac_2', models.IntegerField(null=True)),
                ('Bac_3', models.IntegerField(null=True)),
                ('Bac_4', models.IntegerField(null=True)),
                ('Bac_5', models.IntegerField(null=True)),
                ('Luong_BHXH_moi', models.IntegerField(null=True)),
                ('Luong_moi', models.IntegerField(null=True)),
                ('CL_Luong_BHXH_PA_1', models.IntegerField(null=True)),
                ('CL_Luong_moi_PA_1', models.IntegerField(null=True)),
                ('luong_toi_thieu', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('Nhanvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien')),
                ('Nhom_luong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.TK_ngach')),
            ],
        ),
    ]
