# Generated by Django 2.2 on 2023-03-15 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0013_phuongan_luong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phuongan_luong',
            name='Nhom_luong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luong.bangluong_chinh'),
        ),
    ]
