# Generated by Django 2.2 on 2023-03-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_auto_20230321_1633'),
        ('luong', '0014_auto_20230315_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phuongan_luongbhxh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Luong_BHXH_cu', models.IntegerField(null=True)),
                ('Luong_cu', models.IntegerField(null=True)),
                ('Bac_1', models.IntegerField(null=True)),
                ('Bac_2', models.IntegerField(null=True)),
                ('Bac_3', models.IntegerField(null=True)),
                ('Bac_4', models.IntegerField(null=True)),
                ('Bac_5', models.IntegerField(null=True)),
                ('Luong_BHXH_moi', models.IntegerField(null=True)),
                ('Luong_moi', models.IntegerField(null=True)),
                ('CL_Luong_BHXH', models.IntegerField(null=True)),
                ('CL_Luong_moi', models.IntegerField(null=True)),
                ('luong_toi_thieu', models.IntegerField(null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('Nhanvien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien')),
                ('Nhom_luong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luong.bangluong_chinh')),
                ('Nhom_luongBH', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luong.bangluong_BHXH')),
            ],
        ),
    ]
