# Generated by Django 2.2 on 2023-03-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0015_phuongan_luongbhxh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phuongan_luongbhxh',
            old_name='CL_Luong_BHXH',
            new_name='CL_Luong_BHXH_PA_1',
        ),
        migrations.RenameField(
            model_name='phuongan_luongbhxh',
            old_name='CL_Luong_moi',
            new_name='CL_Luong_moi_PA_1',
        ),
    ]
