# Generated by Django 2.2 on 2023-04-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luong', '0016_auto_20230321_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='hd_laodong',
            name='Ngay_chamdut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
