# Generated by Django 2.2 on 2022-11-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huanluyen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duan_c_giao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='khach_hang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kh', models.CharField(max_length=75)),
                ('content_Kh', models.TextField(blank=True, max_length=2000, null=True)),
                ('image_kh', models.ImageField(blank=True, null=True, upload_to='')),
                ('Leader_kh', models.CharField(blank=True, max_length=75, null=True)),
                ('Leader_img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='giangvien',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='giangvien',
            name='profile',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='loptu_van',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='loptu_van',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
