# Generated by Django 2.2 on 2022-11-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huanluyen', '0002_auto_20221129_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giangvien',
            options={'ordering': ['id', 'name']},
        ),
    ]
