# Generated by Django 2.2 on 2022-12-08 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nhansu', '0003_auto_20221207_2302'),
        ('mota_cv', '0001_initial'),
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Congviec_nangluc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('Muc_quantrong_nluc', models.IntegerField(default=2)),
                ('Muc_thanhthao_nluc', models.IntegerField(default=3)),
                ('Diem_tieuchuan', models.IntegerField()),
                ('stt', models.IntegerField(default=2)),
                ('chucdanh_CV', models.ForeignKey(default=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='mota_cv.Mota_Cv7')),
                ('nangluc_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.Nang_luc_2')),
            ],
            options={
                'ordering': ['chucdanh_CV', 'nangluc_cv', 'name'],
                'unique_together': {('chucdanh_CV', 'nangluc_cv')},
            },
        ),
        migrations.CreateModel(
            name='Danhgia_nluc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Landanhgia_nagluc', models.CharField(blank=True, max_length=20, null=True)),
                ('tu_danhgia_dapung', models.IntegerField(blank=True, null=True)),
                ('Quanly_danhgia', models.IntegerField(blank=True, null=True)),
                ('Ketqua_danhgia', models.IntegerField(blank=True, null=True)),
                ('Diem_tieuchuan', models.IntegerField(blank=True, null=True)),
                ('Diem_dat', models.IntegerField(blank=True, null=True)),
                ('Kha_nang_dapung', models.IntegerField(blank=True, null=True)),
                ('Diem_manh', models.CharField(blank=True, max_length=220, null=True)),
                ('Diem_khacphuc', models.CharField(blank=True, max_length=220, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('Nhanvien_dg_nangluc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien')),
                ('Quanly_dg_nangluc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Quanly')),
                ('TenNangluc_congviec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nangluc.Congviec_nangluc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tong_nl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ketqua_danhgia', models.IntegerField(default=3)),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nangluc.Danhgia_nluc')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
