# Generated by Django 2.2 on 2022-12-18 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
        ('nangluc', '0002_congviec_nangluc_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tong_nl',
            name='Nhanvien_dg_nangluc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien'),
        ),
    ]
