# Generated by Django 2.2 on 2022-12-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0005_auto_20221218_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congviec_nangluc',
            options={'ordering': ['chucdanh_CV', 'nangluc_cv', 'name', 'stt']},
        ),
        migrations.RenameField(
            model_name='danhgia_nluc',
            old_name='Diem_dat',
            new_name='Diem_dgia',
        ),
        migrations.RenameField(
            model_name='danhgia_nluc',
            old_name='Ketqua_danhgia',
            new_name='Ketqua_dapung',
        ),
        migrations.RenameField(
            model_name='danhgia_nluc',
            old_name='Kha_nang_dapung',
            new_name='Ketqua_thongnhat_dg',
        ),
    ]
