# Generated by Django 2.2 on 2022-12-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0006_auto_20221224_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhgia_nluc',
            old_name='Diem_dgia',
            new_name='Diem_dat',
        ),
        migrations.RenameField(
            model_name='danhgia_nluc',
            old_name='Ketqua_dapung',
            new_name='Ketqua_danhgia',
        ),
        migrations.RemoveField(
            model_name='danhgia_nluc',
            name='Ketqua_thongnhat_dg',
        ),
    ]
