# Generated by Django 2.2 on 2022-12-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0007_auto_20221224_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhgia_nluc',
            old_name='Diem_khacphuc',
            new_name='Diem_danhgia',
        ),
        migrations.RenameField(
            model_name='danhgia_nluc',
            old_name='Diem_manh',
            new_name='Ketqua_tile',
        ),
    ]
