# Generated by Django 2.2 on 2022-12-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0008_auto_20221224_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia_nluc',
            name='Kha_nang_dapung',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
