# Generated by Django 2.2 on 2022-12-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0012_auto_20221225_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='congviec_nangluc',
            options={'ordering': ['chucdanh_CV', 'nangluc_cv__loai_nang_luc', 'stt', 'name']},
        ),
    ]
