# Generated by Django 2.2 on 2023-01-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0004_remove_danhgia_nluc_user'),
        ('nangluc', '0013_auto_20221225_2230'),
    ]

    operations = [
    ]
