# Generated by Django 2.2 on 2023-02-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0017_delete_studentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
