# Generated by Django 2.2 on 2023-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0018_delete_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia_nluc',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
