# Generated by Django 2.2 on 2023-02-12 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0023_auto_20230212_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia_nluc_thu',
            name='tu_danhgia_dapung',
            field=models.CharField(default=datetime.datetime(2023, 2, 12, 9, 38, 6, 735585, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
