# Generated by Django 2.2 on 2023-02-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0024_auto_20230212_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='name',
            new_name='Landanhgia_nagluc',
        ),
    ]
