# Generated by Django 2.2 on 2023-02-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0025_auto_20230212_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='email',
            new_name='TenNangluc_congviec',
        ),
    ]
