# Generated by Django 2.2 on 2023-02-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0026_auto_20230212_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='gender',
            new_name='tu_danhgia_dapung',
        ),
    ]
