# Generated by Django 2.2 on 2023-02-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0027_auto_20230212_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='danhgia_nluc_thu',
            old_name='created_at',
            new_name='start_date',
        ),
    ]
