# Generated by Django 2.2 on 2023-02-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0028_auto_20230212_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='created_at',
            new_name='start_date',
        ),
    ]
