# Generated by Django 2.2 on 2023-02-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0030_auto_20230212_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Landanhgia_nagluc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
