# Generated by Django 2.2 on 2023-02-12 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0032_auto_20230212_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='TenNangluc_congviec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nangluc.Congviec_nangluc'),
        ),
    ]
