# Generated by Django 2.2 on 2023-02-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0035_auto_20230212_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia_nluc_thu',
            name='tu_danhgia_dapung',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
