# Generated by Django 2.2 on 2023-02-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0036_auto_20230212_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Quanly_danhgia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
