# Generated by Django 2.2 on 2023-02-12 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_nhan_vien_da_nghiviec'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nangluc', '0037_studentdata_quanly_danhgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='Diem_danhgia',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Diem_dat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Diem_tieuchuan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Ketqua_danhgia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Ketqua_tile',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Kha_nang_dapung',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Nhanvien_dg_nangluc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='Quanly_dg_nangluc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Quanly'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentData_thayso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Landanhgia_nagluc', models.CharField(blank=True, max_length=20, null=True)),
                ('tu_danhgia_dapung', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('Quanly_danhgia', models.IntegerField(blank=True, null=True)),
                ('TenNangluc_congviec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nangluc.Congviec_nangluc')),
            ],
        ),
    ]
