# Generated by Django 2.2 on 2023-02-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_nhan_vien_da_nghiviec'),
        ('nangluc', '0038_auto_20230212_2306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='danhgia_nluc',
            unique_together={('Landanhgia_nagluc', 'Nhanvien_dg_nangluc', 'TenNangluc_congviec')},
        ),
    ]
