# Generated by Django 2.2 on 2023-03-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0039_auto_20230219_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='Diem_danhgia',
            new_name='Diem_tu_danhgia',
        ),
    ]
