# Generated by Django 2.2 on 2023-03-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0041_auto_20230307_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Danhgia_nluc_thu',
        ),
        migrations.RemoveField(
            model_name='studentdata_thayso',
            name='TenNangluc_congviec',
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
        migrations.DeleteModel(
            name='StudentData_thayso',
        ),
    ]
