# Generated by Django 2.2 on 2023-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nangluc', '0042_auto_20230307_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgia_nluc',
            name='Diem_danhgia',
        ),
        migrations.AddField(
            model_name='danhgia_nluc',
            name='Diem_tu_danhgia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
