# Generated by Django 2.2 on 2022-12-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0002_auto_20221129_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nang_luc_2',
            old_name='label_nang_luc',
            new_name='label',
        ),
    ]
