# Generated by Django 2.2 on 2023-01-05 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0003_auto_20221207_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loai_kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KPI_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('kpo', models.CharField(blank=True, max_length=100, null=True)),
                ('ma_kpi', models.CharField(blank=True, max_length=4, null=True)),
                ('moTa_kpi', models.CharField(max_length=1000, null=True)),
                ('tan_xuat_d_gia', models.CharField(blank=True, choices=[('th', 'Tháng'), ('qu', 'Quý'), ('na', 'Năm')], default='Tháng', max_length=20, null=True)),
                ('chi_tieu', models.DecimalField(decimal_places=1, max_digits=7)),
                ('ngaytao', models.DateField(auto_now_add=True)),
                ('ngay_update', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('label', models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('I', 'info'), ('W', 'warning'), ('S', 'success'), ('G', 'good')], max_length=1, null=True)),
                ('loai_kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Loai_kpi')),
            ],
            options={
                'ordering': ['loai_kpi', 'ma_kpi'],
            },
        ),
    ]
