# Generated by Django 2.2 on 2023-01-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0004_kpi_list_loai_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donvi_tinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='kpi_list',
            name='tan_xuat_d_gia',
            field=models.CharField(blank=True, choices=[('Tháng', 'Tháng'), ('Quý', 'Quý'), ('Quý', 'Năm')], default='Tháng', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='kpi_list',
            name='Donvi_tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Donvi_tinh'),
        ),
    ]
