# Generated by Django 2.2 on 2023-01-06 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0005_auto_20230106_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi_list',
            name='Donvi_tinh',
        ),
        migrations.AddField(
            model_name='kpi_list',
            name='donvi_tinh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.Donvi_tinh'),
        ),
    ]
