# Generated by Django 2.2 on 2023-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0006_auto_20230106_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tieuchuan_KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Gioihanduoi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Diem_chitieu_tang', models.IntegerField()),
                ('Diem_chitieu_giam', models.IntegerField()),
            ],
        ),
    ]
