# Generated by Django 2.2 on 2023-01-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0007_tieuchuan_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_list',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
