# Generated by Django 2.2 on 2023-01-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0009_kpi_list_su_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nhom_KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
            ],
        ),
    ]
