# Generated by Django 2.2 on 2023-01-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0010_nhom_kpi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tochuc_Sudung_KPI_NL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='nang_luc_2',
            name='su_dung',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kpi_list',
            name='tochuc_Sudung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Tochuc_Sudung_KPI_NL'),
        ),
        migrations.AddField(
            model_name='nang_luc_2',
            name='tochuc_Sudung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Tochuc_Sudung_KPI_NL'),
        ),
    ]
