# Generated by Django 2.2 on 2023-01-10 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0011_auto_20230110_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nang_luc',
        ),
    ]
