# Generated by Django 2.2 on 2023-01-10 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0012_delete_nang_luc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ho_congviec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='kpi_list',
            name='ho_congviec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ho_congviec'),
        ),
        migrations.AddField(
            model_name='nang_luc_2',
            name='ho_congviec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ho_congviec'),
        ),
    ]
