# Generated by Django 2.2 on 2023-01-10 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0013_auto_20230110_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ho_congviec',
            name='ma_ho_cv',
            field=models.CharField(default=datetime.datetime(2023, 1, 10, 13, 53, 29, 2588, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
    ]
