# Generated by Django 2.2 on 2023-02-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0014_ho_congviec_ma_ho_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='don_vi',
            name='nv_dv',
            field=models.FileField(blank=True, null=True, upload_to='CNNV_dv'),
        ),
    ]
