# Generated by Django 2.2 on 2023-03-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0015_auto_20230207_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TK_ngach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhom', models.IntegerField(blank=True, null=True)),
                ('diem', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
