# Generated by Django 2.2 on 2023-03-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0017_auto_20230311_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tk_ngach',
            name='bac_1_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tk_ngach',
            name='bac_2_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tk_ngach',
            name='bac_3_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tk_ngach',
            name='bac_4_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tk_ngach',
            name='bac_5_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tk_ngach',
            name='di_tk_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tk_ngach',
            name='heso_gian_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tk_ngach',
            name='lan_gian_BHXH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
