# Generated by Django 2.2 on 2023-03-17 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0018_auto_20230314_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loai_vanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='vanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namne', models.CharField(blank=True, max_length=70, null=True)),
                ('ma_vanban', models.CharField(blank=True, max_length=4, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('file_name', models.FileField(blank=True, null=True, upload_to='')),
                ('MoTa_nangluc', models.CharField(max_length=4000)),
                ('ngay_tao', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('label', models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('I', 'info'), ('W', 'warning'), ('S', 'success'), ('g', 'good')], max_length=1, null=True)),
                ('su_dung', models.BooleanField(default=False)),
                ('loai_vanban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Loai_vanban')),
                ('tochuc_Sudung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Tochuc_Sudung_KPI_NL')),
            ],
            options={
                'ordering': ['loai_vanban', 'namne'],
            },
        ),
    ]
