# Generated by Django 2.2 on 2023-03-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0019_loai_vanban_vanban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vanban',
            options={'ordering': ['loai_vanban', 'name']},
        ),
        migrations.RenameField(
            model_name='vanban',
            old_name='MoTa_nangluc',
            new_name='MoTa_vanban',
        ),
        migrations.RenameField(
            model_name='vanban',
            old_name='namne',
            new_name='name',
        ),
    ]
