# Generated by Django 2.2 on 2023-04-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0020_auto_20230317_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vanban',
            options={'ordering': ['id', 'loai_vanban', 'name']},
        ),
    ]
