# Generated by Django 2.2 on 2023-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhansu', '0021_auto_20230408_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi_list',
            name='chi_tieu',
            field=models.DecimalField(decimal_places=1, max_digits=12),
        ),
    ]
