# Generated by Django 2.2 on 2022-11-20 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhansu', '0001_initial'),
        ('mota_cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tonghopdinhbien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donvi_tinh', models.CharField(choices=[('Ngày', 'Ngày'), ('Lần', 'Lần'), ('Ca', 'Ca'), ('Hồ sơ', 'Hồ sơ')], max_length=20, null=True)),
                ('tan_xuat_lviec', models.CharField(choices=[('Ngày', 'Ngày'), ('Tuần', 'Tuần'), ('Tháng', 'Tháng'), ('Quý', 'Quý'), ('6 Tháng', '6 Tháng'), ('Năm', 'Năm')], max_length=20, null=True)),
                ('chucdanh_dinhbien', models.CharField(blank=True, max_length=90, null=True)),
                ('dinhbien_hienco', models.IntegerField(blank=True, null=True)),
                ('laodong_hc_hienco', models.IntegerField(blank=True, null=True)),
                ('laodong_ca_hienco', models.IntegerField(blank=True, null=True)),
                ('Lao_dong_ngoaids', models.IntegerField(blank=True, null=True)),
                ('laodong_hc_dinhbien', models.IntegerField(blank=True, null=True)),
                ('laodong_ca_dinhbien', models.IntegerField(blank=True, null=True)),
                ('tong_dinhbien', models.IntegerField(blank=True, null=True)),
                ('chenhlech_dbien', models.IntegerField(blank=True, null=True)),
                ('Tong_phut_1nam', models.IntegerField(blank=True, null=True)),
                ('ghichu', models.CharField(blank=True, max_length=500, null=True)),
                ('bo_phan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Bo_phan')),
                ('chuc_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota_cv.Mota_Cv')),
                ('don_vi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Don_vi')),
                ('to_nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.To_nhom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dinhbien_HC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donvi_tinh', models.CharField(choices=[('Ngày', 'Ngày'), ('Lần', 'Lần'), ('Ca', 'Ca'), ('Hồ sơ', 'Hồ sơ')], max_length=20, null=True)),
                ('tan_xuat_lviec', models.CharField(choices=[('Ngày', 'Ngày'), ('Tuần', 'Tuần'), ('Tháng', 'Tháng'), ('Quý', 'Quý'), ('6 Tháng', '6 Tháng'), ('Năm', 'Năm')], max_length=20, null=True)),
                ('Noi_dung_cviec', models.TextField(max_length=1000)),
                ('khoiluong_nam', models.IntegerField(blank=True, null=True)),
                ('sophut_th_1lan', models.IntegerField(blank=True, null=True)),
                ('Tong_phut_1nam', models.IntegerField(blank=True, null=True)),
                ('dinhbienhc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='đinhbiênhc')),
                ('Ngaytao', models.DateTimeField(auto_now_add=True)),
                ('Ngay_update', models.DateTimeField(auto_now=True)),
                ('bo_phan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Bo_phan')),
                ('chuc_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota_cv.Mota_Cv')),
                ('chucdanh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinhbien.tonghopdinhbien')),
                ('don_vi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Don_vi')),
                ('to_nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.To_nhom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dinhbien_ca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donvi_tinh', models.CharField(choices=[('Ngày', 'Ngày'), ('Lần', 'Lần'), ('Ca', 'Ca'), ('Hồ sơ', 'Hồ sơ')], max_length=20, null=True)),
                ('tan_xuat_lviec', models.CharField(choices=[('Ngày', 'Ngày'), ('Tuần', 'Tuần'), ('Tháng', 'Tháng'), ('Quý', 'Quý'), ('6 Tháng', '6 Tháng'), ('Năm', 'Năm')], max_length=20, null=True)),
                ('Noi_dung_cviecca', models.TextField(max_length=1000)),
                ('laodong_ca_1', models.IntegerField(blank=True, null=True)),
                ('laodong_ca_2', models.IntegerField(blank=True, null=True)),
                ('laodong_ca_3', models.IntegerField(blank=True, null=True)),
                ('khoiluongsp_ca_1', models.IntegerField(editable=False)),
                ('khoiluongsp_ca_2', models.IntegerField(editable=False)),
                ('khoiluongsp_ca_3', models.IntegerField(editable=False)),
                ('sophut_th_1lanc', models.IntegerField(blank=True, null=True)),
                ('Thoigian_yc_ca_1', models.IntegerField(blank=True, null=True)),
                ('Thoigian_yc_ca_2', models.IntegerField(blank=True, null=True)),
                ('Thoigian_yc_ca_3', models.IntegerField(blank=True, null=True)),
                ('Tong_phut_1namc', models.IntegerField(blank=True, null=True)),
                ('dinhbienca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Định biên ca')),
                ('bo_phan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Bo_phan')),
                ('chuc_vu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mota_cv.Mota_Cv')),
                ('chucdanh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinhbien.tonghopdinhbien')),
                ('don_vi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Don_vi')),
                ('to_nhom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhansu.To_nhom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
