# Generated by Django 2.2 on 2023-04-09 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhansu', '0023_auto_20230409_1642'),
        ('mota_cv', '0004_mota_cv7_chuc_danh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enroll', '0007_auto_20230321_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khung_kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('chi_tieu', models.IntegerField(default=1)),
                ('ti_trong', models.DecimalField(blank=True, decimal_places=2, default=0.05, max_digits=3, null=True)),
                ('stt', models.IntegerField(default=2)),
                ('chucdanh_CV', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mota_cv.Mota_Cv7')),
                ('kpi_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.KPI_list')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['chucdanh_CV', 'kpi_cv__loai_kpi', 'kpi_cv__ma_kpi', 'stt'],
                'unique_together': {('chucdanh_CV', 'kpi_cv')},
            },
        ),
        migrations.CreateModel(
            name='Danhgia_KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Landanhgia_KPI', models.CharField(blank=True, max_length=20, null=True)),
                ('tu_danhgia_dapung', models.IntegerField(blank=True, null=True)),
                ('Quanly_danhgia', models.IntegerField(blank=True, null=True)),
                ('Ketqua_danhgia', models.IntegerField(blank=True, null=True)),
                ('Tile_hoanthanh', models.IntegerField(blank=True, null=True)),
                ('Diem_congviec', models.IntegerField(blank=True, null=True)),
                ('Diem_trongso', models.CharField(blank=True, max_length=220, null=True)),
                ('Ketqua_tile', models.CharField(blank=True, max_length=220, null=True)),
                ('Nhanvien_dg_KPI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Nhan_vien')),
                ('Ten_kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kpi_bsc.Khung_kpi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Nhanvien_dg_KPI', 'Ten_kpi'],
            },
        ),
    ]
