# Generated by Django 2.2 on 2022-11-20 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mota_cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billingaddress1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('zip', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('Don_vi_tinh', models.CharField(choices=[('dg', ' đồng'), ('kwx', 'kwh/tấn xi măng'), ('kwc', 'kcal/kg clanhke'), ('kwx', 'tr.đồng/người'), ('kwx', 'Tấn'), ('kwx', 'ngày'), ('kg', 'kg'), ('%', '%')], default='%', max_length=3, null=True)),
                ('Tan_xuat_d_gia', models.CharField(choices=[('tháng', 'Tháng'), ('qu', 'Quý'), ('na', 'Năm')], default='Tháng', max_length=20, null=True)),
                ('Ti_trong', models.DecimalField(decimal_places=1, default='20', max_digits=5)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('co', 'Con Cún con')], max_length=2)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger'), ('I', 'info'), ('W', 'warning'), ('S', 'success')], max_length=1)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('LoaiCV', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mota_cv.Mota_Cv')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=20)),
                ('Chi_tieu', models.IntegerField(default=1)),
                ('Ket_qua', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bsc.Item1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Billingaddress1', to='bsc.Billingaddress1')),
                ('items', models.ManyToManyField(to='bsc.OrderItem1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
