# Generated by Django 3.1.6 on 2022-02-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('educator', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('excerpt', models.TextField(max_length=300)),
                ('number_lessons', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='course_pictures')),
                ('video', models.FileField(upload_to='course-file')),
            ],
        ),
    ]
