# Generated by Django 2.2 on 2023-02-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0007_studentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
