# Generated by Django 2.2 on 2022-11-20 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhansu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BHXHTN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOTEN', models.CharField(blank=True, max_length=150, null=True)),
                ('SOBHXH', models.CharField(blank=True, max_length=10, null=True)),
                ('SOKCB', models.CharField(blank=True, max_length=10, null=True)),
                ('NGAYSINH', models.DateField(blank=True, null=True)),
                ('NAMSINH', models.IntegerField(blank=True, null=True)),
                ('GIOITINH', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3, null=True)),
                ('NOIKHAI', models.CharField(blank=True, max_length=120, null=True)),
                ('NOICAP', models.CharField(blank=True, max_length=12, null=True)),
                ('NGAYCMND', models.DateTimeField(blank=True, null=True)),
                ('DIACHI', models.CharField(blank=True, max_length=120, null=True)),
                ('TINH_LH', models.IntegerField(blank=True, null=True)),
                ('HUYEN_LH', models.IntegerField(blank=True, null=True)),
                ('XA_LH', models.IntegerField(blank=True, null=True)),
                ('DIACHIHK', models.CharField(blank=True, max_length=120, null=True)),
                ('MAPB', models.CharField(blank=True, max_length=20, null=True)),
                ('MADT', models.CharField(blank=True, choices=[('Cận nghèo', 'Cận nghèo'), ('Người có công', 'Người có công'), ('Hộ gia đình ', 'Hộ gia đình')], max_length=30, null=True)),
                ('TUNGAY', models.DateTimeField(blank=True, null=True)),
                ('DENNGAY', models.DateTimeField(blank=True, null=True)),
                ('SOTHANG', models.CharField(blank=True, max_length=20, null=True)),
                ('TUTHANG', models.CharField(blank=True, max_length=2, null=True)),
                ('DENTHANG', models.CharField(blank=True, max_length=2, null=True)),
                ('TYLE', models.DecimalField(blank=True, decimal_places=2, default=4.5, max_digits=5, null=True)),
                ('TYLE_NSNN', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('TYLEDONG', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ML_DK', models.IntegerField(blank=True, null=True)),
                ('HSL_DK', models.IntegerField(blank=True, null=True)),
                ('ML_dong', models.IntegerField(blank=True, null=True)),
                ('HSL', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True)),
                ('PA', models.IntegerField(blank=True, null=True)),
                ('ML', models.IntegerField(blank=True, default=1490000, null=True)),
                ('MA_BV', models.CharField(blank=True, max_length=4, null=True)),
                ('MA_TINH', models.CharField(blank=True, max_length=5, null=True)),
                ('MAVUNGSS', models.CharField(blank=True, max_length=40, null=True)),
                ('TAMTRU', models.CharField(blank=True, max_length=120, null=True)),
                ('SOBL', models.IntegerField(blank=True, null=True)),
                ('NGAYBL', models.DateTimeField(auto_now_add=True, null=True)),
                ('SDT', models.IntegerField(blank=True, null=True)),
                ('MA_CA', models.CharField(blank=True, max_length=120, null=True)),
                ('GHICHU', models.CharField(blank=True, max_length=120, null=True)),
                ('GIAM_DO_CHET', models.BooleanField(default=False)),
                ('DANTOC', models.ForeignKey(blank=True, default='Kinh', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Dan_toc')),
                ('MA_TINHCMT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Tinh_que')),
                ('QUOCTICH', models.ForeignKey(blank=True, default='Việt Nam', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Quocgia')),
                ('phuong_xa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Phuong_xa')),
                ('quan_huyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Quan_huyen')),
                ('tinh_thanh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Tinh')),
            ],
        ),
    ]
