# Generated by Django 2.2 on 2022-12-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhan_vien',
            name='vitriquanly',
            field=models.BooleanField(default=False),
        ),
    ]
