# Generated by Django 2.2 on 2023-01-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_nhan_vien_vitriquanly'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhan_vien',
            name='da_nghiviec',
            field=models.BooleanField(default=False),
        ),
    ]
