# Generated by Django 2.2 on 2023-03-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_nhan_vien_da_nghiviec'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhan_vien',
            name='Luong_BHXH_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='Luong_cu',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
