# Generated by Django 2.2 on 2023-03-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20230321_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhan_vien',
            options={'ordering': ['ngay_vao_dv']},
        ),
        migrations.RenameField(
            model_name='nhan_vien',
            old_name='Luong_BHXH_c',
            new_name='Luong_BHXH_cu',
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='Luong_BHXH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='Luong_cb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='Nang_luc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='So_ngayphep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
