# Generated by Django 2.2 on 2023-03-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20230321_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhan_vien',
            name='Bac_cu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='Bang_luong_cu',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='Heso_cu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='nhan_vien',
            name='Ngay_giu_lg_cu',
            field=models.DateField(blank=True, null=True),
        ),
    ]
