# Generated by Django 2.2 on 2023-02-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_ajax', '0002_studentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
