# Generated by Django 2.2 on 2022-11-20 16:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhansu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mota_Cv7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_Nhom_CV', models.TextField(blank=True, max_length=115, null=True)),
                ('ma_tenvitri', models.TextField(blank=True, max_length=10, null=True)),
                ('Ten_vitri_full', models.TextField(blank=True, max_length=110, null=True)),
                ('Ten_theoluong', models.TextField(blank=True, max_length=100, null=True)),
                ('mota_Cong_viec', models.FileField(blank=True, null=True, upload_to='mota_CV_2022')),
                ('Captren', models.CharField(blank=True, max_length=200, null=True)),
                ('Donvi_Captren', models.CharField(blank=True, max_length=100, null=True)),
                ('Mucdich_cv', models.CharField(blank=True, max_length=900, null=True)),
                ('Qhe_captren', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_cungcap', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_capduoi', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_nn_xahoi', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_khachhang', models.CharField(blank=True, max_length=500, null=True)),
                ('Nh_vu_ket_qua', models.CharField(blank=True, max_length=10000000, null=True)),
                ('Trach_nhiem', models.CharField(blank=True, max_length=50000, null=True)),
                ('Mucdo_anhhuong', models.CharField(blank=True, max_length=300, null=True)),
                ('Ptien_laodong', models.CharField(blank=True, default='Máy móc, thiết bị, phương tiện để đảm bảo hoàn thành nhiệm vụ được theo theo qui định của Công ty', max_length=300, null=True)),
                ('tong_diem7', models.IntegerField(blank=True, null=True)),
                ('Nhom_luong', models.IntegerField(blank=True, null=True)),
                ('Loai_laodong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.Loai_laodong')),
                ('Ycau_CNTT_24', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_CNTT_24')),
                ('Ycau_Ngoaingu_23', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_Ngoaingu_23')),
                ('Yeu_to_1_trinh_do', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_1_trinh_do')),
                ('Yeu_to_2_Ky_nang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_2_Ky_nang')),
                ('Yeu_to_3_Trach_nhiem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_3_Trach_nhiem')),
                ('Yeu_to_4_Anh_huong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_4_Anh_huong')),
                ('Yeu_to_5_Sangtao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_5_Sangtao')),
                ('Yeu_to_6_Giaotiep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_6_Giaotiep')),
                ('Yeu_to_7_DK_lamviec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_7_DK_lamviec')),
                ('Yeu_to_khac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Yeu_to_khac')),
                ('bo_phan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Bo_phan')),
                ('don_vi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Don_vi')),
                ('ten_nghe_NNDH', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ten_ngheDH')),
                ('to_nhom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.To_nhom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mota_Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ten_Nhom_CV', models.TextField(blank=True, max_length=115, null=True)),
                ('ma_tenvitri', models.TextField(blank=True, max_length=10, null=True)),
                ('Ten_vitri_full', models.TextField(blank=True, max_length=110, null=True)),
                ('Ten_theoluong', models.TextField(blank=True, max_length=100, null=True)),
                ('ten_nghe_NNDH', models.TextField(blank=True, max_length=100, null=True)),
                ('Phan_loai', models.CharField(choices=[('CN', 'Công nhân'), ('NV', 'Nhân viên'), ('QLCT', 'Quản lý Công ty'), ('QLĐV', 'Quản lý đơn vị'), ('QLBP', 'Quản lý bộ phận'), ('QLT01', 'Quản lý Tổ 1'), ('QLT01.', 'Quản lý Tổ 3'), ('QLT02', 'Quản lý Tổ 2'), ('QL', 'Quản lý 3'), ('SPEC', 'Khác')], default='%', max_length=20, null=True)),
                ('mota_Cong_viec', models.FileField(blank=True, null=True, upload_to='mota_CV_2022')),
                ('Captren', models.CharField(blank=True, max_length=300, null=True)),
                ('diadiem_lv', models.CharField(blank=True, max_length=300, null=True)),
                ('Mucdich_cv', models.CharField(blank=True, max_length=900, null=True)),
                ('Qhe_captren', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_cungcap', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_capduoi', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_nn_xahoi', models.CharField(blank=True, max_length=500, null=True)),
                ('Qhe_khachhang', models.CharField(blank=True, max_length=500, null=True)),
                ('Nh_vu_ket_qua', ckeditor.fields.RichTextField()),
                ('Trach_nhiem', models.CharField(blank=True, max_length=1000000, null=True)),
                ('Mucdo_anhhuong', models.CharField(blank=True, max_length=300, null=True)),
                ('Ptien_laodong', models.CharField(blank=True, max_length=300, null=True)),
                ('Dieu_kienlaodong', models.CharField(blank=True, default='Máy móc, thiết bị, phương tiện để đảm bảo hoàn thành nhiệm vụ được theo theo qui định của Công ty', max_length=300, null=True)),
                ('ycau_kynang_khac', models.CharField(blank=True, max_length=300, null=True)),
                ('tong_diem', models.IntegerField()),
                ('bo_phan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Bo_phan')),
                ('don_vi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Don_vi')),
                ('mt_laodong_41', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Mt_laodong_41')),
                ('muc_ah_cty_11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Muc_ah_cty_11')),
                ('muc_ah_nv_12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Muc_ah_nv_12')),
                ('muc_rui_ro_42', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Muc_rui_ro_42')),
                ('to_nhom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nhansu.To_nhom')),
                ('ycau_CNTT_24', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_CNTT_24')),
                ('ycau_Ngoaingu_23', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_Ngoaingu_23')),
                ('ycau_cuongdo_35', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_cuongdo_35')),
                ('ycau_doclap_33', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_doclap_33')),
                ('ycau_giaotiep_34', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_giaotiep_34')),
                ('ycau_k_nghiem_22', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_k_nghiem_22')),
                ('ycau_kehoach_31', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_kehoach_31')),
                ('ycau_sangtao_32', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_sangtao_32')),
                ('ycau_trinhdocm_21', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nhansu.Ycau_trinhdocm_21')),
            ],
            options={
                'ordering': ['Ten_Nhom_CV'],
            },
        ),
    ]
