# Generated by Django 2.2 on 2023-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mota_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mota_cv7',
            name='Qhe_capduoi',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='mota_cv7',
            name='Qhe_captren',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='mota_cv7',
            name='Qhe_cungcap',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='mota_cv7',
            name='Qhe_khachhang',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='mota_cv7',
            name='Qhe_nn_xahoi',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
