# Generated by Django 2.2 on 2023-03-16 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mota_cv', '0003_chuc_danh'),
    ]

    operations = [
        migrations.AddField(
            model_name='mota_cv7',
            name='chuc_danh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mota_cv.Chuc_danh'),
        ),
    ]
